spring:
  application:
    name: cloud-config-test-server
  cloud:
    config:
      uri: http://localhost:7070
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
server:
  port: 9999

custom:
  property-name: default-property
  value: 1
  list:
    - 1
    - 2
    - 3
    - 4
